config/routes.rb
FdPj::Application.routes.draw do

  resources :fds

  get "fds/new"

  get "fds/create"

  get "fds/index"

  get "fds/update"

  get "fds/destroy"

  get "fds/show"

    root to: 'fds#index'

end

app/models/fd.rb
class Fd < ActiveRecord::Base
  attr_accessible :addr, :city, :customername, :depositamount, :dateofbirth, :noy, :openedon, :pan, :pin, :roi, :sex, :md, :interest
  
before_save :set_openedon    
  def set_openedon
    self.openedon = Date.today.strftime("%d/%m/%Y")
  end  


before_save :calculate_md
  def calculate_md
    self.openedon = Date.today
     case self.noy
      when 12
        self.md = self.openedon + 1.year
      when 24
        self.md = self.openedon + 2.years
      when 36
        self.md = self.openedon + 3.years
      when 48
        self.md = self.openedon + 4.years
      else
        self.md = self.openedon + 5.years      
     end
  end

before_save :calculate_age
  def calculate_age
    self.age = ((DateTime.now - self.dateofbirth)/365)
  end

before_save :calculate_roi
  def calculate_roi
     if self.age >= 58 && self.age < 75 && self.noy == 12
       self.roi += 0.5
     elsif self.age >= 58 && self.age < 75 && self.noy == 24
       self.roi += 0.5
     elsif self.age >= 58 && self.age < 75 && self.noy == 36
       self.roi += 0.5
     elsif self.age >= 58 && self.age < 75 && self.noy == 48
       self.roi += 0.5
     elsif self.age >= 58 && self.age < 75 && self.noy == 60
       self.roi += 0.25     
     elsif self.age >= 75 && self.noy == 12
       self.roi += 1.0
     elsif self.age >= 75 && self.noy == 24
       self.roi += 1.0
     elsif self.age >= 75 && self.noy == 36
       self.roi += 1.0
     elsif self.age >= 75 && self.noy == 48
       self.roi += 0.75
     elsif self.age >= 75 && self.noy == 60
       self.roi += 0.25     
     else
       self.roi
     end
  end

before_save :calculate_interest
  def calculate_interest
    self.roi = self.roi/100
    self.interest = ((self.depositamount.round * self.roi)/12).round
  end

before_save :set_roi
  def set_roi
    self.roi = self.roi * 100
  end
  
  validates :customername, presence: true, format: { with: %r{^[A-Z][a-zA-Z\s]*} }

  #validates_numericality_of :pin, presence: true, length: { maximum: 6 }  

  #validates :openedon, presence: true  

  #validates :addr, presence: true

  #validates :pan, :uniqueness => true, presence:true, format: { with: %r{^[A-Z]{5}\d{4}[A-Z]{1}} }, length: {maximum: 10}

  validates_inclusion_of :dateofbirth,
      :in => Date.civil(1900, 1, 1)..Date.today,
      :message => "Must be between 1900 and now"   

  #validates :age, presence: true    

  validates :city, presence: true  

  validates :sex, presence: true    

  validates :depositamount, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fds_controller.rb
class FdsController < ApplicationController
  def new
    @fd = Fd.new
  end

  def create
    sleep 2
    @fd = Fd.new(params[:fd])
    if @fd.save
      flash[:success] = "FD Account Opened Successfully!"
      redirect_to fds_path
    else
      flash[:error] = "Couldn't Open FD"  
      render  'new'
    end
  end

  def edit
    @fd = Fd.find(params[:id])
  end

  def index
    @fd = Fd.order('created_at DESC').paginate(:page => params[:page], :per_page => 8)
  end

  def update
    @fd = Fd.find(params[:id])
      if @fd.update_attributes(params[:fd])
        flash[:success] = "Updated your FD Account"
        redirect_to fds_path(@fd)
      else
        flash[:alert] ="Fill the necessary fields"
        render 'edit'
      end
  end

  def destroy
    @fd = Fd.find(params[:id])
    @fd.destroy
    flash[:notice] = "Your FD Account Get Deleted"
    redirect_to fds_path
  end

  def show
    @fd = Fd.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fds_helper.rb
module FdsHelper
end

app/views/fds/_form.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/money.jpg) no-repeat;
background-position: center;
background-size: 100%;
}
</style>

<script type="text/javascript">
function addit(){
if(document.getElementById("fd_noy").value=="12Months")
{
document.getElementById("fd_roi").value="9.5%"
}
if(document.getElementById("fd_noy").value=="24Months")
{
document.getElementById("fd_roi").value="10%"
}
if(document.getElementById("fd_noy").value=="36Months")
{
document.getElementById("fd_roi").value="10.5%"
}
if(document.getElementById("fd_noy").value=="48Months")
{
document.getElementById("fd_roi").value="11%"
}
if(document.getElementById("fd_noy").value=="60Months")
{
document.getElementById("fd_roi").value="11.5%"
}
}
</script>

<%= form_for @fd do |f| %>  
 
<% if @fd.errors.any? %>
<h4>Couldn't open FD Account</h4>
<ul>
<% @fd.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</ul>
<% end %>
    <h5><%= f.label :customer_name, class:'required' %>
    <%= f.text_field :customername, :placeholder =>'Customer Name' %></h5>

    <h5><%= f.label :date_of_birth, class:'required' %>
    <%= f.date_select :dateofbirth, { :include_blank => true, :start_year => 1900, :end_year => 2014 } %></h5>
   
    <h5><%= f.label :sex %>
    <%= f.select :sex, options_for_select(%w[Male Female]), { :include_blank => true} %></h5>

    <h5><%= f.label :city %>
    <%= f.text_field :city, :placeholder =>'City' %></h5>   

    <h5><%= f.label :deposit_amount, class:'required' %>
    <%= f.text_field :depositamount, :placeholder =>'0.00' %></h5>
   
    <h5><%= f.label :opened_on %>
    <%= f.text_field :openedon, :disabled => true, :value => Date.today.strftime("%d/%m/%Y") %></h5>

    <div>
    <h5><%= f.label :Periods, class:'required' %>
    <select  name="fd[noy]" id="fd_noy" onChange="addit()">
    <option value="">Select Periods</option>
    <option value="12Months">12Months</option>
    <option value="24Months">24Months</option>
    <option value="36Months">36Months</option>
    <option value="48Months">48Months</option>
    <option value="60Months">60Months</option>
    </select><h5>
  </div>
  <div>
    <h5><%= f.label :Rate_Of_Interest %>
    <input type="text" name="fd[roi]" id="fd_roi" value="" readonly="readonly" onChange="addit()">
    <span class="help-block">auto-generated</span></h5>
  </div>
      
  </div>
    <%= f.submit "Open FD", class: "btn btn-primary", data: {disable_with: "Opening..."} %>
    <% end %>
  </div>
</div>

app/views/fds/create.html.erb
<h1>Create</h1>
<p>
  This is the Create page for FD Account.
</p>

app/views/fds/destroy.html.erb
<%= render 'form' %>

app/views/fds/edit.html.erb
<h1>Edit FD Account</h1>
<%= render 'form' %>

app/views/fds/index.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/cash.jpg) no-repeat;
background-position: center right;
background-size: 100%;
}
</style>

<h2>Fixed Deposit </h2>

<div> 
  <%= link_to "Open FD Account", fds_new_path, class: "btn btn-primary" %> </div>
</br>

<h6 class= "alert alert-info"><%= page_entries_info @fd %></h6>

<table cellpadding = "5" cellspacing ="5" >
  <tr>            
    <th>Opened On</th>
    <th>Customer Name</th>    
    <th>Deposit Amount</th> 
    <th>Customer Age</th>
    <th>Rate Of Interest</th>     
    <th>Periods</th>
    <th>Monthly Interest</th>
    <th>Maturity Date</th>       
  </tr>
  <% @fd.each do |f| %>
    <tr>                
      <td><%= f.openedon.strftime("%d/%m/%Y")%></td>
      <td><%= link_to f.customername, fd_path(f) %></td>  
      <td><%= f.depositamount %></td>
      <td><%= f.age %></td>
      <td><%= f.roi %>%</td>
      <td><%= f.noy %></td>
      <td><%= f.interest %></td>
      <td><%= f.md.strftime("%d/%m/%Y") %></td>      
      <% end %></td>         
    </tr>  
</table>
<br/>

<%= will_paginate @fd %>

app/views/fds/new.html.erb
<h1>New FD Account</h1>
<%= render 'form' %>

app/views/fds/show.html.erb
<style>
body{
padding-top: 60px;
background: url(/assets/moneybag.jpg) no-repeat;
background-position: center;
background-size: 100%;
}
</style>

<br />
<h1><%= link_to "Fixed Deposit", fds_path %></h1>
<br />
<div class="hero-unit">
<h5><strong>Customer Name</strong> : <%= @fd.customername %></h5>
<h5><strong>Age</strong> : <%= @fd.age %></h5>

<div class = "span6 offset6">
      <%= link_to(edit_fd_path(@fd), class: "btn btn-primary") do %>
   <i class="icon-pencil icon-white"> </i> Edit
   <% end %>
   <%= link_to(fd_path(@fd), class: "btn btn-danger", method: :delete, confirm: "Are You Sure?") do %>
   <i class="icon-trash icon-white"> </i> Delete
   <% end %>       
    </div>
<hr>
   
<div class="row">
   <div class="span6 customer_left_span_properties">
   <h4><span class="customer">Account details</span></h4>
   <div class="row">
   <div class="span3">
   <strong>Opened On</strong>
   </div>
   <div class="span3"> : <%= @fd.openedon.strftime("%d/%m/%Y") %></div>
   </div>
   
   <div class="row">
   <div class="span3">
   <strong>Deposit Amount</strong>
   </div>
   <div class="span3"> : <%= @fd.depositamount %></div>
   </div>

   <div class="row">
   <div class="span3">   
   <strong>Periods</strong>
   </div>
   <div class="span3"> : <%= @fd.noy %></div>
   </div>

   <div class="row">
   <div class="span3">
   <strong>Rate Of Interest</strong>
   </div>
   <div class="span3"> : <%= @fd.roi %></div>
   </div>

   <div class="row">
   <div class="span3">   
   <strong>Monthly Interest</strong>
   </div>
   <div class="span3"> : <%= @fd.interest %></div>
   </div>
  
   <div class="row">
   <div class="span3">
   <strong>Maturity Date</strong>
   </div>
   <div class="span3"> : <%= @fd.md.strftime("%d/%m/%Y") %></div>
   </div>
   </div>
   </div>
   </div>
</hr>
</div>
</div>

app/views/fds/update.html.erb
<h1>Update FD Account</h1>
<%= render 'form' %>

app/views/layouts/_footer.html.erb
<footer class="footer">  
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FIXED DEPOSIT",fds_path, id: "logo" %>
    </div>
  </div>
   
       
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fixed Deposit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  	<%= render :partial => 'layouts/header' %>
    <div id="main">
      <%= yield %>
    </div>
    <%= render :partial => 'layouts/footer' %>
  </body>
</html>